version: '3.13'

services:
  postgres:
    image: postgres:15
    container_name: comclassify_postgres
    environment:
      POSTGRES_USER: comclassify_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comclassify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comclassify_user -d comclassify"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: comclassify_backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://comclassify_user:password@postgres:5432/comclassify

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: comclassify_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

volumes:
  postgres_data:
